name: data_strings
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  quiver: ^3.2.2
  collection: ^1.18.0
  uuid: ^4.5.1
  pocketbase: ^0.18.1
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.2
  http: ^1.2.2
  fl_chart: ^0.70.2
  csv: ^6.0.0
  file_picker: ^8.3.7


dev_dependencies:
  hive_generator:  ^1.1.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
